export const icons = {
  google: require('./google.png'),
  copy: require('./copy.png'),
  googleSm: require('./google_sm.png'),
  appleSm: require('./apple_sm.png'),
  checkbox: require('./checkbox.png'),
  back: require('./back.png'),
  home: require('./home.png'),
  plusCircle: require('./plus_circle.png'),
  helpCircle: require('./help_circle.png'),
  circle:require('./circle.png'),
  check:require('./check.png'),
  search:require('./search.png'),

  user: require('./user.png'),
  info: require('./info.png'),
  compose: require('./compose.png'),
  plusFilled: require('./plus_filled.png'),
  camera: require('./camera.png'),
  cloud: require('./cloud.png'),
  library: require('./library.png'),
  arrowDown: require('./arrow_down.png'),
  walk: require('./walk.png'),
  bike: require('./bike.png'),
  car: require('./car.png'),
  filePlus: require('./file_plus.png'),
  trash: require('./trash.png'),
  bin: require('./bin.png'),
  link: require('./link.png'),
  audio: require('./audio.png'),
  editFilled: require('./edit_filled.png'),
  play: require('./play.png'),
  star: require('./star.png'),
  starFilled: require('./star_filled.png'),
  starUnfilled: require('./star_unfilled.png'),
  dots: require('./dots.png'),
  square: require('./square.png'),
  checked: require('./checked.png'),
  stop: require('./stop.png'),
  globe: require('./globe.png'),
  bell: require('./bell.png'),
  map: require('./map.png'),
  calendar: require('./calendar.png'),
  clock: require('./clock.png'),
  skipPrevious: require('./skip_previous.png'),
  download: require('./download.png'),
  downloaded: require('./downloaded.png'),
  video: require('./video.png'),
  menu: require('./menu.png'),
  openButton: require('./open_button.png'),
  rightArrow: require('./right_arrow.png'),
  logout: require('./logout.png'),
  infoCircle: require('./info_circle.png'),
};
